#!/bin/sh -e

sed -i.heex-indent-backup 's,<\.,<POINT,g;s,</\.,</POINT,g' "$@"
web-mode-indent "$@"
sed -i.heex-indent-backup 's,<POINT,<.,g;s,</POINT,</.,g' "$@"

for file in "$@"; do
    rm "$file.heex-indent-backup"
done
